/* =========================================================================
   data.js
   Todo o CONTEÚDO do site fica aqui. Edite à vontade — nomes, datas, textos,
   apelidos, motivos — sem precisar mexer na lógica em app.js.
   ========================================================================= */

const loveConfig = {
  coupleNames: {
    partner1: "Seu nenêm",
    partner2: "Minha princesa",
  },
  // Data de início do relacionamento. Formato: "AAAA-MM-DDTHH:mm:ss"
  startDate: "2026-04-23T00:00:00",
  letterTitle: "Para a pessoa que mudou o meu mundo...",
  letterParagraphs: [
"Meu amor, hoje parei por alguns instantes para pensar em nós e percebi o quanto a minha vida mudou desde que você chegou. Tudo ficou mais bonito, mais leve e mais cheio de sentido. Escrever esta carta é a forma que encontrei de tentar colocar em palavras um sentimento tão grande que, às vezes, parece impossível de explicar.",

"Lembro-me de cada detalhe da nossa história: o primeiro sorriso que você me deu, o som da sua risada que rapidamente se tornou a minha melodia favorita, as conversas que pareciam fazer o tempo parar e a paz indescritível que sinto toda vez que suas mãos encontram as minhas. Você não é apenas o amor da minha vida; você é o meu lar, o meu porto seguro, o meu refúgio e a minha maior felicidade.",

"Obrigado por ser essa pessoa tão incrível, paciente, carinhosa e dona de um coração tão lindo. Obrigado por cada madrugada de conversa, por cada abraço que faz qualquer problema parecer pequeno, por acreditar em mim quando nem eu mesmo consigo e por me inspirar a ser uma pessoa melhor todos os dias.",

"Quando penso no futuro, não consigo imaginar nada que não tenha você ao meu lado. Quero continuar colecionando memórias, realizando sonhos, superando desafios e construindo a nossa história, sempre de mãos dadas. Porque, para mim, não existe lugar melhor no mundo do que ao seu lado.",

"Se um dia as palavras não forem suficientes para demonstrar tudo o que sinto, espero que você consiga enxergar o meu amor em cada gesto, em cada cuidado e em cada olhar. Você é o melhor presente que a vida me deu, e todos os dias agradeço por ter você comigo.",

"Com todo o amor que existe em mim, hoje, amanhã e para sempre. ❤️"

  ],
  signature: "Com todo o meu amor, para sempre seu.",
  proposalQuestion: "Você aceita viver essa história de amor comigo para sempre?",
  proposalSuccessMessage: "A resposta mais feliz da minha vida! Eu te amo daqui até a eternidade! ❤️",
};

const loveReasons = [
  "Seu sorriso ilumina o meu dia.",
  "Você sempre sabe como me fazer rir.",
  "Sua bondade me inspira.",
  "Você me ouve com interesse genuíno.",
  "Você apoia os meus sonhos.",
  "Você tem os olhos mais bonitos.",
  "Você me faz sentir segura.",
  "Seus abraços são os melhores.",
  "Você é incrivelmente atencioso.",
  "Você desperta o melhor em mim.",
  "Você é meu melhor amigo.",
  "Você me aceita como eu sou.",
  "Seu amor pela aventura.",
  "A forma como você cuida dos outros.",
  "Sua criatividade me surpreende.",
  "Você torna até os momentos comuns especiais.",
  "Seu senso de humor.",
  "A forma como você me olha.",
  "Você é tão paciente.",
  "Você nunca desiste de nós.",
  "Você é meu maior incentivador.",
  "Sua inteligência.",
  "Você é um ótimo cozinheiro.",
  "Você é meu confidente.",
  "Você me surpreende das melhores formas.",
  "Você topa tentar coisas novas.",
  "Seu otimismo é contagiante.",
  "Você é incrivelmente dedicado.",
  "Sua lealdade.",
  "Você me faz sentir valorizada.",
  "Sua risada é contagiante.",
  "Você me torna uma pessoa melhor.",
  "Seu espírito aventureiro.",
  "Você sempre está lá quando preciso de você.",
  "Sua paixão pela vida.",
  "A forma como você segura minha mão.",
  "Você é um ouvinte incrível.",
  "Sua generosidade.",
  "Você me respeita.",
  "Você é honesto comigo.",
  "Você é minha rocha.",
  "Você me faz sentir querida.",
  "Seus beijos são mágicos.",
  "Você é minha pessoa favorita.",
  "Sua resiliência.",
  "Você é meu cúmplice.",
  "Sua força.",
  "Você me faz sentir viva.",
  "Sua dedicação ao nosso relacionamento.",
  "Você é sempre honesto comigo.",
  "Seu coração caloroso.",
  "Você torna cada dia mais brilhante.",
  "Seu senso de estilo.",
  "Você é minha alma gêmea.",
  "Seu espírito aventureiro.",
  "Você sempre tem as melhores ideias.",
  "Você é minha inspiração.",
  "Seu altruísmo.",
  "Você me entende.",
  "Você me faz sentir especial.",
  "Sua atitude positiva.",
  "Você é tão carinhoso.",
  "Você é meu conforto.",
  "Seu sorriso é contagiante.",
  "Você é meu parceiro em tudo.",
  "Sua risada me faz feliz.",
  "Você é meu porto seguro.",
  "Sua espontaneidade.",
  "Você me faz sentir amada.",
  "Você é incrivelmente atencioso.",
  "Você sempre arranja tempo pra mim.",
  "Você é minha pessoa favorita para conversar.",
  "Você me faz sentir importante.",
  "Sua lealdade significa o mundo pra mim.",
  "Você é meu melhor amigo e amante.",
  "Você é meu apoio constante.",
  "Seu calor humano.",
  "Você me faz sentir compreendida.",
  "Você é minha combinação perfeita.",
  "Sua paciência comigo.",
  "Você é meu maior fã.",
  "Você me faz rir como ninguém.",
  "Sua natureza amorosa.",
  "Você torna a vida divertida.",
  "Você sempre está lá por mim.",
  "Sua consideração.",
  "Você faz meu coração acelerar.",
  "Você é tudo pra mim.",
  "Seu encorajamento.",
  "Você é minha maior aventura.",
  "Você me faz sentir em casa.",
  "Sua ternura.",
  "Você me faz sorrir.",
  "Sua dedicação a nós.",
  "Você é meu para sempre.",
  "Você torna a vida digna de ser vivida.",
  "Você é meu motivo de sorrir.",
  "Você me faz sentir completa.",
  "Seu amor é minha força.",
  "Você é meu único e verdadeiro amor.",
];

const loveNicknames = [
  { name: "Minha princesa", emoji: "👑", description: "Dona de toda beleza e realeza do meu mundo." },
  { name: "Minha mulher", emoji: "🌹", description: "Forte, inteligente e o grande amor da minha vida." },
  { name: "Minha flor", emoji: "🌸", description: "Que perfuma meus dias e enche minha vida de cores." },
  { name: "Minha gostosa", emoji: "🔥", description: "Minha eterna paixão física e de alma." },
  { name: "Minha fofinha", emoji: "🧸", description: "O aconchego mais dócil e fofo que existe." },
  { name: "Meu bb", emoji: "🍼", description: "Quem eu quero mimar, cuidar e proteger pra sempre." },
  { name: "Meu amor", emoji: "❤️", description: "O sentimento mais forte e sincero que carrego." },
  { name: "Minha jóia rara", emoji: "💎", description: "Preciosa demais, um presente enviado por Deus." },
  { name: "Minha vida", emoji: "🌱", description: "A minha própria razão e alegria de viver." },
  { name: "Minha namorada", emoji: "💍", description: "Minha melhor escolha e minha companheira de vida." },
  { name: "Minha cheirosa", emoji: "✨", description: "Dona do perfume que me fascina e acalma." },
  { name: "Minha abusada", emoji: "😜", description: "Do jeitinho marrento e provocativo que eu sou louco." },
  { name: "Minha exibida", emoji: "💃", description: "Linda de todos os ângulos e orgulho do meu coração." },
  { name: "Minha safada", emoji: "😏", description: "Que me faz perder o juízo com apenas um olhar." },
  { name: "Meu bem", emoji: "💕", description: "O bem mais valioso que eu poderia desejar." },
  { name: "Minha gatinha", emoji: "🐱", description: "Manhosa, linda e extremamente apaixonante." },
  { name: "Minha luz", emoji: "☀️", description: "Que clareia meus caminhos até nos momentos mais escuros." },
  { name: "Minha calma", emoji: "🧘‍♀️", description: "O porto seguro onde minha tempestade se acalma." },
  { name: "Minha perfeição", emoji: "🎯", description: "Não mudaria uma única linha em você." },
  { name: "Minha maior benção que Deus me deu", emoji: "🙏", description: "A prova diária de que as preces são ouvidas." },
  { name: "Minha maravilhosa", emoji: "🌟", description: "Que brilha e encanta com toda sua doçura." },
  { name: "Meu raio de sol", emoji: "☀️", description: "O calor que aquece minhas manhãs." },
  { name: "Minha cúmplice", emoji: "🗺️", description: "Parceira oficial de todas as risadas e loucuras." },
  { name: "Minha gata selvagem", emoji: "🐾", description: "Cheia de personalidade, charme e paixão." },
  { name: "Meu porto seguro", emoji: "⚓", description: "Onde meu coração sempre quer ancorar." },
  { name: "Minha dengoza predileta", emoji: "🥰", description: "Quem tem o colo e o dengo mais gostosos." },
  { name: "Minha deusa grega", emoji: "🏛️", description: "Uma escultura perfeita esculpida pelo amor." },
  { name: "Meu chuchuzinho", emoji: "🥒", description: "O apelido clássico, brega e cheio de carinho." },
  { name: "Minha rainha", emoji: "👑", description: "Comanda com soberania e amor o meu coração." },
  { name: "Meu trevo de quatro folhas", emoji: "🍀", description: "A minha maior e melhor sorte da vida inteira." },
  { name: "Minha razão de sorrir", emoji: "😊", description: "Só de pensar em você o sorriso vem fácil." },
  { name: "Minha pititica", emoji: "🐣", description: "Meu pequeno pedaço de doçura e alegria." },
  { name: "Meu docinho de coco", emoji: "🥥", description: "A sobremesa mais doce da minha rotina." },
  { name: "Minha inspiração diária", emoji: "✨", description: "O motivo pelo qual eu quero ser alguém melhor todos os dias." },
  { name: "Meu par ideal", emoji: "🧩", description: "A peça que faltava para completar o meu quebra-cabeça." },
];

const PRESET_NOTES = [
  {
    id: "preset-1",
    text: "Lembrete do dia: Você é a pessoa mais preciosa de todo o universo e eu tenho o maior orgulho de te ter do meu lado! ❤️",
    author: "Seu Amor",
    color: "amber",
    sticker: "👑",
    date: "A todo momento",
    rotation: -2,
    likes: 5,
  },
  {
    id: "preset-2",
    text: "Vale um beijo na testa bem carinhoso e um abraço apertado de 5 minutos para recarregar todas as suas energias. 😘",
    author: "Seu Amor",
    color: "pink",
    sticker: "💌",
    date: "Validade: Eterna",
    rotation: 3,
    likes: 8,
  },
  {
    id: "preset-3",
    text: "Prometo que sempre que você tiver um dia difícil, eu vou estar bem aqui com chocolate, carinho e sua comida favorita para te fazer sorrir! 🍫",
    author: "Seu Amor",
    color: "purple",
    sticker: "✨",
    date: "Sempre",
    rotation: -1,
    likes: 12,
  },
  {
    id: "preset-4",
    text: "Amo o som da sua risada, o jeito como seus olhos brilham quando você fala de algo que gosta e a calmaria que você traz pro meu peito.",
    author: "Seu Amor",
    color: "rose",
    sticker: "💖",
    date: "Todos os segundos",
    rotation: 2,
    likes: 15,
  },
];

const NOTE_COLORS = [
  { id: "amber", label: "Amarelo" },
  { id: "pink", label: "Rosa" },
  { id: "purple", label: "Roxo" },
  { id: "rose", label: "Vermelho" },
  { id: "teal", label: "Verde" },
];

const NOTE_STICKERS = ["❤️", "💖", "✨", "👑", "🌹", "💌", "🧸", "🍿", "🐈", "💑"];

const FALLING_WORDS_POOL = [
  "EU TE AMO", "TE AMO", "❤️", "AMO VOCÊ", "MEU AMOR", "MINHA VIDA", "AMOR",
  "MINHA PRINCESA", "MEU ANJO", "COISA LINDA", "PRA SEMPRE", "MEU MUNDO",
  "RAZÃO DA MINHA VIDA", "GOSTOSA", "MARAVILHOSA", "PERFEITA", "NAMORADA LINDA",
  "XODÓ", "TE ADORO", "MEU TUDO", "MINHA MENINA", "TE AMO MUITO", "PRINCESA",
  "FLOR", "FOFINHA", "BB", "JÓIA RARA", "CHEIROSA", "ABUSADA", "EXIBIDA",
  "SAFADA", "MEU BEM", "GATINHA", "MINHA LUZ", "MINHA CALMA", "DEUSA",
  "LINDAMOR", "💖", "✨", "💕", "🌹", "💘", "👑",
];

const FALLING_HEARTS_POOL = ["❤️", "💖", "💕", "🌹", "💘", "✨", "🌸", "💌", "💑"];

const FALLING_FONT_CLASSES = ["font-sans-bold", "font-serif-italic", "font-script", "font-mono-tight"];

const FALLING_COLORS_POOL = [
  "#ffffff", "#ffe4e6", "#fecdd3", "#fbcfe8", "#f472b6",
  "#fff1f2", "#fff5f5", "#f43f5e", "#ec4899", "#e11d48",
];
